I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script2.rpy", line 38, in script
    m"Hi there, ILY. Welcome back to the GRID."
Exception: Sayer 'm' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script2.rpy", line 38, in script
    m"Hi there, ILY. Welcome back to the GRID."
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 678, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Applications/renpy-7.3.5-sdk/renpy/ast.py", line 576, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 'm' is not defined.

Darwin-19.5.0-x86_64-i386-64bit
Ren'Py 7.3.5.606
SoftWar - DEMO 1.0
Thu Jun 11 12:47:57 2020
